version: 2
jobs:
  build:
    
    working_directory: ~/podam

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: podam-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: podam-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: src/testreport
      
      - store_artifacts:
          path: src/testoutput.jar
